<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dosis.ttf" />
    <None Remove="logo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GMap.NET.WinPresentation" Version="2.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="fronts\Dosis.ttf" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="logo.jpg" />
  </ItemGroup>

</Project>
