<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <NoWarn>NU1701</NoWarn>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Dosis.ttf" />
    <None Remove="Images\image_ecfd22 - Copier.png" />
    <None Remove="Images\image_ecfd22.png" />
    <None Remove="Images\Info-bulle.png" />
    <None Remove="Images\Smart_territories_logo.png" />
    <None Remove="Images\wind-best - Copier.png" />
    <None Remove="Images\wind-best.png" />
    <None Remove="Images\wind.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
    <PackageReference Include="ProEssentials.Chart.Net80.Wpf" Version="10.0.0.22" />
    <PackageReference Include="Syncfusion.SfChart.WPF" Version="33.2.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\Dosis.ttf" />
    <Resource Include="Images\image_ecfd22 - Copier.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Info-bulle.png" />
    <Resource Include="Images\Smart_territories_logo.png" />
    <Resource Include="Images\wind-best - Copier.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\wind.png" />
  </ItemGroup>

</Project>
